/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspecialidadesIndexRouteImport } from './routes/especialidades.index'
import { Route as EspecialidadesEspecialidadeRouteImport } from './routes/especialidades.$especialidade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesIndexRoute = EspecialidadesIndexRouteImport.update({
  id: '/especialidades/',
  path: '/especialidades/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspecialidadesEspecialidadeRoute =
  EspecialidadesEspecialidadeRouteImport.update({
    id: '/especialidades/$especialidade',
    path: '/especialidades/$especialidade',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/especialidades/$especialidade': typeof EspecialidadesEspecialidadeRoute
  '/especialidades/': typeof EspecialidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/especialidades/$especialidade': typeof EspecialidadesEspecialidadeRoute
  '/especialidades': typeof EspecialidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/especialidades/$especialidade': typeof EspecialidadesEspecialidadeRoute
  '/especialidades/': typeof EspecialidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/especialidades/$especialidade' | '/especialidades/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/especialidades/$especialidade' | '/especialidades'
  id: '__root__' | '/' | '/especialidades/$especialidade' | '/especialidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspecialidadesEspecialidadeRoute: typeof EspecialidadesEspecialidadeRoute
  EspecialidadesIndexRoute: typeof EspecialidadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades/': {
      id: '/especialidades/'
      path: '/especialidades'
      fullPath: '/especialidades/'
      preLoaderRoute: typeof EspecialidadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/especialidades/$especialidade': {
      id: '/especialidades/$especialidade'
      path: '/especialidades/$especialidade'
      fullPath: '/especialidades/$especialidade'
      preLoaderRoute: typeof EspecialidadesEspecialidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspecialidadesEspecialidadeRoute: EspecialidadesEspecialidadeRoute,
  EspecialidadesIndexRoute: EspecialidadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
